### ISSUE TITLE
Can't seem to get this to work with replica set

### ISSUE THREAD

**Issue by ben-ihealth** [denodrivers/deno_mongo#110]
I wonder if anyone has problem using https://deno.land/x/mongo@v0.11.0/mod.ts connectWithUri() with replica set in deno 1.3.2. The same URI works fine with mongo-native/mongoose in node.js.  However, I keep getting the error when using deno mongo.  Actually, the error is not thrown until making CRUD calls (findOne, find, and etc).  Here is the URI:

```
"mongodb://NAME:PASSWORD@mongodb.node1.prod.xxxxxxxxxxx.com:27017,mongodb.node2.prod.xxxxxxxxxxx.com:27017,mongodb.node3.prod.xxxxxxxxxxx.com:27017/DBNAME?replicaSet=rs0.prod"

```
Here is the error:
<img width="1241" alt="Screen Shot 2020-09-06 at 10 07 36 AM" src="https://user-images.githubusercontent.com/24441273/92419546-0b107a00-f123-11ea-9cc1-a557679666ce.png">

I tried both using client.connectWithUri() and client.connectWithOptions() with the same error.

// connectWithUri
```
 // this uri is not using ip but also got same error using ip:port. e.g: x.x.x.x;27017
const uri = 'mongodb://NAME:PASSWORD@mongodb.node1.prod.xxxxxxxxxxx.com:27017,mongodb.node2.prod.xxxxxxxxxxx.com:27017,mongodb.node3.prod.xxxxxxxxxxx.com:27017/DBNAME?replicaSet=rs0.prod'
client.connectWithUri(uri);
```

// connectWithOptions
```
client.connectWithOptions({
      hosts: [
        'mongodb.node1.prod.xxxxxxxxxxxxx.com:27017',  // same error using ip:port. e.g: x.x.x.x:27017
        'mongodb.node2.prod.xxxxxxxxxxxxx.com:27017',
        'mongodb.node3.prod.xxxxxxxxxxxxx.com:27017'
      ],
      username: 'USERNAME',
      password: 'PASSWORD',
      replSetName: 'rs0.prod',  // same error with or without this option
      directConnection: true  // same error with or without this option
})
```

**Comment by benluu** [comment]
This seems to be related to issue https://github.com/manyuanrong/deno_mongo/issues/41

**Comment by playerx** [comment]
I've the same issue and I can't use it in production without replica set support

**Comment by erfanium** [comment]
I don't have any problem with MongoDB atlas default replica set servers. i'm going close this issue, tell me if this problem still exists
