### ISSUE TITLE
Failed to lookup address information: nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by marcodali** [denodrivers/deno_mongo#141]
I have this error

`error: Uncaught (in promise) Error: failed to lookup address information: nodename nor servname provided, or not known
    at processResponse (core.js:223:11)
    at Object.jsonOpAsync (core.js:240:12)
    at async Object.connect (deno:cli/rt/30_net.js:224:13)
    at async MongoClient.connect (client.ts:20:18)`

Trying connect with Atlas using the following code:

const client = new MongoClient();
await client.connect(
  `mongodb+srv://${env.dbUser}:${env.dbPass}@${env.dbHost}/`,
);

deno 1.5.4
mongo@v0.20.0

**Comment by marcodali** [comment]
<img width="313" alt="Screen Shot 2020-12-02 at 2 34 22" src="https://user-images.githubusercontent.com/70110654/100848650-09670180-3447-11eb-80ca-390dee0cc2c4.png">

I found this, but not sure how to use it...

**Comment by hackers267** [comment]
The protocol `mongodb+srv` don't surpport now, but may surpport the next version.

**Comment by dl90** [comment]
I also tried to use mongo atlas and it was throwing the same error
connecting to mongodb locally seems ok, but looks like theres no support for auth atm

**Comment by JanNemcik** [comment]
Can you please confirm the date of this feature? thanks

**Comment by Jason5Lee** [comment]
This seem to be a issue related to macOS, I also met it.
Related: https://github.com/instructure/canvas-data-loader/issues/3

**Comment by manyuanrong** [comment]
closed by #198
