### ISSUE TITLE
Getting disconnect from mongo db when trying to use database.listConnectionNames

### ISSUE THREAD

**Issue by edward653** [denodrivers/deno_mongo#155]
So, I'm investigating this and it's a work in progress, but I wanted to get something up here to see if anybody has any pointers. I've a reasonable little project coming along and it's interacting with my local mongo instance extensively - except this one call.

Serverside, my mongo instance is logging the following before killing the connection:

2021-01-05T21:11:00.427+0000 I NETWORK [conn76] DBException handling request, closing client connection: IllegalOpMsgFlag: Message contains illegal flags value: Ob00000000000000000000000001110101

In Deno land, my app is logging the following:

error: Uncaught (in promise) AssertionError
    throw new AssertionError(msg);
          ^
    at assert (asserts.ts:152:11)
    at WireProtocol.receive (protocol.ts:80:7)

Sadly, I can't seem to replicate this at all using a minimal implementation - which shouts that something is awry with my code, not deno_mongo.

My base attempt to replicate this, below, works fine - as do the tests when I check out the code.

"""
import { MongoClient } from "../deps.ts";

const client = new MongoClient();
await client.connect("mongodb://localhost:27017");

const db = client.database("blah");

console.log(await db.listCollectionNames());
"""

Within the body of my code though, it fails as above.. the pertinent lines all look the same. I'm at a loss.

This is using deno_mongo 0.20.1 and:

deno 1.6.2 (release, x86_64-apple-darwin)
v8 8.8.278.2
typescript 4.1.3

**Comment by edward653** [comment]
Okay - one more thing which may help. I've been ferretting around trying to debug the difference between the call from my test effort vs my real app - using a local checked out copy of deno_mongo I've added some console.log of the chunked data being sent in WireProtocol, logged just after the call returns from the serializeMessage method as follows:

    console.log(`ED: CHUNKS: ${chunks}`);

Test harness call for listCollectionNames gives the following output (processed fine):

ED: CHUNKS: 117,0,0,0,1,0,0,0,0,0,0,0,221,7,0,0,0,0,0,0,0,96,0,0,0,16,108,105,115,116,67,111,108,108,101,99,116,105,111,110,115,0,1,0,0,0,8,110,97,109,101,79,110,108,121,0,1,8,97,117,116,104,111,114,105,122,101,100,67,111,108,108,101,99,116,105,111,110,115,0,1,16,98,97,116,99,104,83,105,122,101,0,1,0,0,0,2,36,100,98,0,11,0,0,0,115,112,97,99,101,45,103,97,109,101,0,0

Output when called from main app (server kills it) - the single different int in bold:

ED: CHUNKS: 117,0,0,0,**3**,0,0,0,0,0,0,0,221,7,0,0,0,0,0,0,0,96,0,0,0,16,108,105,115,116,67,111,108,108,101,99,116,105,111,110,115,0,1,0,0,0,8,110,97,109,101,79,110,108,121,0,1,8,97,117,116,104,111,114,105,122,101,100,67,111,108,108,101,99,116,105,111,110,115,0,1,16,98,97,116,99,104,83,105,122,101,0,1,0,0,0,2,36,100,98,0,11,0,0,0,115,112,97,99,101,45,103,97,109,101,0,0

**Comment by manyuanrong** [comment]
> Okay - one more thing which may help. I've been ferretting around trying to debug the difference between the call from my test effort vs my real app - using a local checked out copy of deno_mongo I've added some console.log of the chunked data being sent in WireProtocol, logged just after the call returns from the serializeMessage method as follows:
> 
> ```
> console.log(`ED: CHUNKS: ${chunks}`);
> ```
> 
> Test harness call for listCollectionNames gives the following output (processed fine):
> 
> ED: CHUNKS: 117,0,0,0,1,0,0,0,0,0,0,0,221,7,0,0,0,0,0,0,0,96,0,0,0,16,108,105,115,116,67,111,108,108,101,99,116,105,111,110,115,0,1,0,0,0,8,110,97,109,101,79,110,108,121,0,1,8,97,117,116,104,111,114,105,122,101,100,67,111,108,108,101,99,116,105,111,110,115,0,1,16,98,97,116,99,104,83,105,122,101,0,1,0,0,0,2,36,100,98,0,11,0,0,0,115,112,97,99,101,45,103,97,109,101,0,0
> 
> Output when called from main app (server kills it) - the single different int in bold:
> 
> ED: CHUNKS: 117,0,0,0,**3**,0,0,0,0,0,0,0,221,7,0,0,0,0,0,0,0,96,0,0,0,16,108,105,115,116,67,111,108,108,101,99,116,105,111,110,115,0,1,0,0,0,8,110,97,109,101,79,110,108,121,0,1,8,97,117,116,104,111,114,105,122,101,100,67,111,108,108,101,99,116,105,111,110,115,0,1,16,98,97,116,99,104,83,105,122,101,0,1,0,0,0,2,36,100,98,0,11,0,0,0,115,112,97,99,101,45,103,97,109,101,0,0

It seems that the requestId is different. If other data packets are exchanged before this, the requestId will increase automatically. Maybe the problem is not here

**Comment by edward653** [comment]
Ah that makes perfect sense, yes. There be are a couple of interactions over the same mongo connection prior to the listCollections. 

Thanks - I’ll keep digging.

**Comment by edward653** [comment]
Closing this for now - reordering the interactions with mongo caused the listCollectionNames to succeed - with one of my later (previously working) calls to die with the same issue.

Will embark on a bit of trial and error and see what I can work out, but I think it fair to say there isn't an issue specifically with listCollectionNames.
