### ISSUE TITLE
Empty async iterator yields undefined

### ISSUE THREAD

**Issue by canac** [denodrivers/deno_mongo#157]
I'm on version v0.20.1 and am trying to asynchronously iterate over the results of a find query, something like this:

```ts
const items = db.collection('items').find();
for await (const doc of items) {
  console.log(items);
}
```

When the query finds no documents, the asynchronous iterator yields a single `undefined` value instead of yielding nothing.

Maybe in `CommandCursor::[Symbol.asyncIterator]`, this line

```ts
yield await this.next();
```

needs changed to something like

```ts
const value = await this.next();
if (value !== undefined) {
  yield this.next();
}
```

I'd be happy to put together a PR for that change if I'm understanding the problem correctly.

**Comment by manyuanrong** [comment]
Of course, welcome to submit pr
