### ISSUE TITLE
It doesn't seem to authenticate

### ISSUE THREAD

**Issue by johnknoop** [denodrivers/deno_mongo#162]
I'm trying to connect to my cluster in Atlas using this code:

```ts
await client.connect({
	servers: [
		{ host: '______.n6nuf.azure.mongodb.net', port: 27017 },
		{ host: '______.n6nuf.azure.mongodb.net', port: 27017 },
		{ host: '______.n6nuf.azure.mongodb.net', port: 27017 },
	],
	replSetName: '______',
	dbName: 'admin',
	auth: {
		user: 'myUserName',
		password: 'myPassword'
	}
});

const db = client.database("testdb");
const coll = db.collection('testcollection');

const result = await coll.find();
```

For the property `replSetName` I pass the same value as I normally use for the `replicaSet` parameter in a MongoDB connection URL.

But I get this error:

> error: Uncaught Error: MongoError: {"operationTime":{"$timestamp":"6916151343866445825"},"ok":0,"errmsg":"command find requires authentication","code":13,"codeName":"Unauthorized","$clusterTime":{"clusterTime":{"$timestamp":"6916151343866445825"},"signature":{"hash":"5AAAABFvcGVyYXRpb25UaW1lAAEAAAABG/tfAW9rAAAAAAAAAAAAAmVycm1zZwAlAAAAY29tbWFuZCBmaW5kIHJlcXVpcmVzIGF1dGhlbnRpY2F0aW9uABBjb2RlAA0AAAACY29kZU5hbWUADQAAAFVuYXV0aG9yaXplZAADJGNsdXN0ZXJUaW1lAFgAAAARY2x1c3RlclRpbWUAAQAAAAEb+18Dc2lnbmF0dXJlADMAAAAFaGFzaAAUAAAAAMfsqXUO2EWzNf7pOL3JKbR0U8s7EmtleUlkAAQAAABsv+dfAAAA","keyId":{"low":4,"high":1609023340,"unsigned":false}}}}
      throw new MongoError(maybeError);
            ^
    at WireProtocol.commandSingle (protocol.ts:34:13)
    at async FindCursor.executor (find.ts:17:24)
    at async FindCursor.execute (cursor.ts:34:21)
    at async FindCursor.next (cursor.ts:48:7)
    at async FindCursor.[Symbol.asyncIterator] (cursor.ts:67:13)     
    at async FindCursor.forEach (cursor.ts:73:22)

**Comment by manyuanrong** [comment]
v0.21.0 is supported

**Comment by johnknoop** [comment]
@manyuanrong 

After upgrading to v0.21.0, I now get this exception:

![image](https://user-images.githubusercontent.com/3394270/104425442-f9cbf400-5580-11eb-9a1e-97f2701d601f.png)

Any idea what might be wrong?

**Comment by manyuanrong** [comment]
replicaSet does not yet support
