### ISSUE TITLE
Uncaught (in promise) ConnectionRefused

### ISSUE THREAD

**Issue by manojap** [denodrivers/deno_mongo#170]
O got this error, the MongoDB work with Mongoose and Node very well

error: Uncaught (in promise) ConnectionRefused: No connection could be made because the target machine actively refused it. (os error 10061)

**Comment by hemedani** [comment]
I have the same problem too

```typescript
import { MongoClient } from "https://deno.land/x/mongo@v0.21.2/mod.ts";

const client = new MongoClient();
const db = await client.connect("mongodb://localhost:27017/kayran");
export default db;
```

**Comment by hemedani** [comment]
I drop my db and run project everything is fixed. I think it's because of wrong indexes ...

**Comment by michaeldesu** [comment]
@hemedani maybe the OP's error is different to yours.

I had the same error as originally reported. @manojap try using:

`await client.connect("mongodb://127.0.0.1:27017");`

which worked for me.

**Comment by danipv54** [comment]
# Just  specify 
``` ("mongodb://127.0.0.1:27017")```

**Comment by michaeldesu** [comment]
this issue should be closed, and probably the example documentation updated to reflect using the IP address instead
