### ISSUE TITLE
Error: connection timed out

### ISSUE THREAD

**Issue by seilon-zhang** [denodrivers/deno_mongo#175]
I set it completely according to the tutorial, and the host address is correct, but every connection is timed out. When I connect in node, I can connect

**Comment by manyuanrong** [comment]
You can post the key code, maybe some details are wrong

**Comment by seilon-zhang** [comment]
`const client: MongoClient = new MongoClient();
    await client.connect("mongodb://192.168.18.100:27017");
    return client.database(this.database);`

**Comment by seilon-zhang** [comment]
I have found the problem, the original version is v0.21.0, I changed to v0.21.2, the connection is normal, but output another error!
`thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli\fmt_errors.rs:211:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by erfanium** [comment]
@seilon-zhang Can you check the latest driver version?
