### ISSUE TITLE
Error: Unknown Host | Mongo Atlas

### ISSUE THREAD

**Issue by JeanVydes** [denodrivers/deno_mongo#176]
When I try to connect to Mongo Altas with this kind of url (mongodb+srv://<username>:<password>@cluster0.qe6ou.mongodb.net/<dbname>?retryWrites=true&w=majority) Deno Mongo returns me an error: Unknown Host.
How can i fix this?

![5aa90b6c209de715aacb21c3242cacb6](https://user-images.githubusercontent.com/46204992/106346641-81567a00-6286-11eb-8e76-8a11fb1bcb73.png)

**Comment by jhowcs** [comment]
Take a look at this issue: https://github.com/denodrivers/deno_mongo/issues/172#issuecomment-770368981

Someone already solved this, using a different way to connect.

**Comment by manyuanrong** [comment]
closed by #198
