### ISSUE TITLE
Error using 'findOne' with free atlas cluster

### ISSUE THREAD

**Issue by tavadur** [denodrivers/deno_mongo#179]
Hey,

I've tested code from example section with free mongodb cluster and I'm getting an error: 

> "errmsg":"noTimeout cursors are disallowed in this atlas tier"

While inserting with '**insertOne()**' everything works fine, but error appears when I'm trying to use '**findOne()**'.

Is that function uses any of noTimeout cursor option mentioned here in section Operational Limitations section / Cursors: [free-shared-limitations](https://docs.atlas.mongodb.com/reference/free-shared-limitations) or something? 

Any idea?

Regards,
Konrad

**Comment by manyuanrong** [comment]
You can use option parameters to change the default option values
```ts
const result = await collection.findOne({}, { noCursorTimeout:false });
```

**Comment by tavadur** [comment]
Hey @manyuanrong,

I've tried your solution and it works fine but I have to add @ts-ignore over the line with **_findOne()_**.

I've found that **_FindOptions_** interface doesn't contains **_noCursorTimeout_** property, is this ok?

```
export interface FindOptions {
  findOne?: boolean;
  skip?: number;
  limit?: number;
  projection?: Document;
  sort?: Document;
}
```

**Comment by manyuanrong** [comment]
Yes, some attributes are missing from the parameter type declaration, which should be improved

**Comment by FSou1** [comment]
@tavadur were you able to run the latest version of the package with the Atlas MongoDb cluster?

**Comment by tavadur** [comment]
@FSou1 yes I was able to connect with latest version. 

I used the way mentioned here: [Couldn’t connect with atlas database #172](https://github.com/denodrivers/deno_mongo/issues/172#issuecomment-770368981)

Instead of using host name from connection string generated under 'Connect' button, you have to pick primary one, like on screen below:

![image](https://user-images.githubusercontent.com/53137941/107846535-c9c47a80-6de4-11eb-8a32-6a87de81fd75.png)

Just click on it, and copy full name. :)

As I can see, an author of solution also answered there, in connection issue: [Couldn’t connect with atlas database #172](https://github.com/denodrivers/deno_mongo/issues/172#issuecomment-778583614).

**Comment by FSou1** [comment]
@tavadur Oh, you are right. I was managed to connect, thx alot.
