### ISSUE TITLE
Find query returns empty value 

### ISSUE THREAD

**Issue by rssaranece94** [denodrivers/deno_mongo#184]
I have tried findOne, insertOne, both works, but find() not working

const client = new MongoClient();
await client.connect('mongodb://127.0.0.1:27017');
const db = client.database('test');
const users = db.collection('users');

tried both combination

const all_users = await users.find({ name: { $ne: null } });
const all_users = await users.find({ });

console.log(all_users);

result --> FindCursor {}  

can you guys help me out of it.

OS: Windows 10
DB: Mongo Server 4.0

**Comment by hackers267** [comment]
Because the result which use find is a cursor, if you want to use it as a array, many you can use it like this:
```
const all_users = await users.find({ name: { $ne: null } }).toArray();
console.log(all_users);
```

**Comment by rssaranece94** [comment]
Thanks for your response works beautifully.
