### ISSUE TITLE
Got Broken Pipe Error very frequently with Deno js - BrokenPipe: Broken pipe (os error 32) 

### ISSUE THREAD

**Issue by ruchirkakkad** [denodrivers/deno_mongo#188]
Getting the below error every day in my localhost and also on aws server. Please help me out to solve this

0|app      |     at async Collection.findOne (https://raw.githubusercontent.com/manyuanrong/deno_mongo/refactor/src/collection/collection.ts:43:12)
0|app      | 2021-03-26T06:15:07.234Z [10] BrokenPipe: Broken pipe (os error 32) 
0|app      |     at unwrapResponse (deno:runtime/js/10_dispatch_minimal.js:60:13)
0|app      |     at sendAsync (deno:runtime/js/10_dispatch_minimal.js:99:12)
0|app      |     at async write (deno:runtime/js/12_io.js:118:20)
0|app      |     at async Object.writeAll (deno:runtime/js/13_buffer.js:224:19)
0|app      |     at async WireProtocol.command (https://raw.githubusercontent.com/manyuanrong/deno_mongo/refactor/src/protocol/protocol.ts:55:7)
0|app      |     at async WireProtocol.commandSingle (https://raw.githubusercontent.com/manyuanrong/deno_mongo/refactor/src/protocol/protocol.ts:31:19)
0|app      |     at async FindCursor.executor (https://raw.githubusercontent.com/manyuanrong/deno_mongo/refactor/src/collection/commands/find.ts:17:24)
0|app      |     at async FindCursor.execute (https://raw.githubusercontent.com/manyuanrong/deno_mongo/refactor/src/protocol/cursor.ts:34:21)
0|app      |     at async FindCursor.next (https://raw.githubusercontent.com/manyuanrong/deno_mongo/refactor/src/protocol/cursor.ts:48:7)
0|app      |     at async Collection.findOne (https://raw.githubusercontent.com/manyuanrong/deno_mongo/refactor/src/collection/collection.ts:43:12)

**Comment by erfanium** [comment]
ref #278
