### ISSUE TITLE
Fetch operations always reutrn "Internal Server Error" bug 

### ISSUE THREAD

**Issue by MohammedWaheeb** [denodrivers/deno_mongo#195]
Hello this is my first time trying deno, and i was trying to create a mini project 
My problem is every time i try to get data the server returns Internal Server Error it happens after the find `statement` 
i am using https://deno.land/x/mongo@v0.22.0/mod.ts
```
const searchContactForms = async (ctx: RouterContext) => {

   const data:ContactForm[] = await dbc.find({ name: { $ne: null } })?.toArray()
  ctx.response.body ={"data":data};
};

```
```
interface ContactForm {
    _id?:string
    name: string;
    email: string;
    phoneNumber: string;
    message: string;
    timestamp:Date

  }
  
```

> {"_id":{"$oid":"608b35fa3a10c379c13194b1"},"email":"tst","message":"tstmsg","name":"name","phoneNumber":"043033","timestamp":{"$date":{"$numberLong":"1619736058759"}}}
-data sample

**Comment by manyuanrong** [comment]
Can you provide more detailed information? And use the least code to reproduce it, for example, you don’t need to work with your web service code
