### ISSUE TITLE
 Uncaught (in promise) Error: MongoError: {"ok":0,"errmsg":"noTimeout cursors are disallowed in this atlas tier","code":8000,"codeName":"AtlasError"}

### ISSUE THREAD

**Issue by pakinming** [denodrivers/deno_mongo#224]
**const count = await users.count({ username: { $ne: null } }); > this ok**
but 
**const user = await users.find().toArray(); not ok**
 Uncaught (in promise) Error: MongoError: {"ok":0,"errmsg":"noTimeout cursors are disallowed in this atlas tier","code":8000,"codeName":"AtlasError"}

**Comment by pakinming** [comment]
version https://deno.land/x/mongo@v0.22.0/mod.ts

**Comment by erfanium** [comment]
Please use a newer version. There is a fix for mongodb atlas in [v0.23.0](https://github.com/denodrivers/deno_mongo/releases/tag/v0.23.0) release

**Comment by GlennGuegan** [comment]
@pakinming I have same problem with v0.23.1. 
To fixed this error, I added options into find function : 
```
const user = await users.find({}, { noCursorTimeout: false}).toArray()
```
It's work fine with Mongo Atlas.
Default deno_mongo have `noCursorTimeout` set to `true`

**Comment by pakinming** [comment]
> @pakinming I have same problem with v0.23.1.
> To fixed this error, I added options into find function :
> 
> ```
> const user = await users.find({}, { noCursorTimeout: false}).toArray()
> ```
> 
> It's work fine with Mongo Atlas.
> Default deno_mongo have `noCursorTimeout` set to `true`

Thank you so much this sulution is work

**Comment by erfanium** [comment]
@manyuanrong Is this a bug? I think so

**Comment by manyuanrong** [comment]
> @manyuanrong Is this a bug? I think so

If you manually create a mongodb server, it can work well. This is the setting of the cloud service, so I don't think it is an issue. But we should use the same default value as other drivers

**Comment by ArnabXD** [comment]
Using v0.29.0 and got the same error

```json
{
    "ok": 0,
    "errmsg": "noTimeout cursors are disallowed in this atlas tier",
    "code": 8000,
    "codeName": "AtlasError"
}
```

```ts
import { MongoClient } from "https://deno.land/x/mongo@v0.29.0/mod.ts";

// ...

const Users = mongo.database().collection<User>("Users")

// ...

const _user = await Users.findOne({ userId: { $eq: user } });
```
