### ISSUE TITLE
`listCollection` fails on Mongo 5

### ISSUE THREAD

**Issue by DerNamenlose** [denodrivers/deno_mongo#232]
I've encountered a weird issue when using `listCollections`, which would always fail on MongoDB 5.0.2 with 

```
Error: MongoError: {"ok":0,"errmsg":"BSON field 'listCollections.batchSize' is an unknown field.","code":40415,"codeName":"Location40415"}
```

This seems to be caused by the `batchSize: 1` in `database.ts:54`. Commenting out that line fixes the issue.

I'm unclear as to why exactly that issue happens. While it seems to never have been part of the request object (at least from what I gather from the MongoDB docs), it didn't cause issues for me before updating to MongoDB 5.

**Comment by manyuanrong** [comment]
Close this issue and transfer to this issue tracking: #244
