### ISSUE TITLE
find error

### ISSUE THREAD

**Issue by hanumanjiblog** [denodrivers/deno_mongo#236]
![Screenshot_1](https://user-images.githubusercontent.com/87318222/130477697-cf0b4243-9aa3-4d55-96cb-461d04688330.png)
![Screenshot_2](https://user-images.githubusercontent.com/87318222/130477702-5a03ded4-fcf2-45fe-8b3f-bbae3c47684c.png)

**Comment by erfanium** [comment]
See #224
