### ISSUE TITLE
Impossible to use operators with findAndModify

### ISSUE THREAD

**Issue by ablause** [denodrivers/deno_mongo#237]
There is a particular reason to have used a generic with in the argument filter instead of "Document" ?

https://github.com/denodrivers/deno_mongo/blob/bbc5fa8134c77957265a13d83c773f401ff23fac/src/collection/collection.ts#L57-L60

**Comment by manyuanrong** [comment]
Using generics can better deduce the types of parameters and help a better development experience. Maybe we can use Document as an alternative type

**Comment by erfanium** [comment]
@manyuanrong the query type should be `Document`, not `Partial<T>`, because using operators ($gt, $lt, ...) will cause type error
