### ISSUE TITLE
Implementation of GridFS

### ISSUE THREAD

**Issue by lucsoft** [denodrivers/deno_mongo#238]
https://docs.mongodb.com/manual/core/gridfs/

GridFS is a very important feature from the nodejs driver and we need this for deno to <3. Its currently the last big thing that blocks me to use mongodb on deno

**Comment by erfanium** [comment]
I would like to work on it but I don't know how GridFS protocol works. Is there any spec about GridFs?

**Comment by manuelaguirre** [comment]
> I would like to work on it but I don't know how gridFS protocol works. Is there any spec for gridFS?

I'd like to help

**Comment by lucsoft** [comment]
@erfanium is there a target version where I can expect this feature?

**Comment by erfanium** [comment]
@lucsoft
I'm not a user of this feature (GridFS) yet, so I can't maintain it. If you interested, you can implement it yourself and make a PR.

**Comment by manuelaguirre** [comment]
Hi @lucsoft . I've been working a bit on this and I have succeeded to implement part of the upload stream.

**Comment by lucsoft** [comment]
@manuelaguirre oh really? this is amazing. 

Do you use ReadableStream? (looking at my Basic Api Interfaces/types)

**Comment by manuelaguirre** [comment]
for the upload I'm using WritableStream

**Comment by lucsoft** [comment]
Oh! Yeah right, I swapped them accidentally.
Can we work together or something?

**Comment by manuelaguirre** [comment]
I'd love to, it's a fairly complex implementation. Do you want me to prep a PR to your branch with what I have done?

**Comment by lucsoft** [comment]
Yes

**Comment by lucsoft** [comment]
@manuelaguirre my part of the implementation is ready (Download Stream, Delete, Find). Can you create the PR for your upload implementation?

i can fix the merge conflicts
