### ISSUE TITLE
[Notice] About this project

### ISSUE THREAD

**Issue by manyuanrong** [denodrivers/deno_mongo#262]
Hello,I hope this library can become a widely used and mature library, but I am currently facing great financial pressure and work troubles. I don’t have a lot of time to maintain this library. I will try my best to cooperate and provide help.

**Comment by Lite5h4dow** [comment]
hi, i would like to help, however i dont know the first thing about interfacing with mongo db without a library. do you have any resources you would reccomend?

**Comment by erfanium** [comment]
@Lite5h4dow 
https://github.com/mongodb/specifications

**Comment by Lite5h4dow** [comment]
@erfanium that's just the specs, I'm not sure how these things work yet. are there no guides on driver creation?

**Comment by erfanium** [comment]
@Lite5h4dow You can checkout official driver implementations.

**Comment by erfanium** [comment]
@manyuanrong 

I think it's better to unpin this issue. it makes others feel that this package does not have any maintainers and worries them, but this is not really the case and a lot has happened during this time.
