### ISSUE TITLE
`GridFSBucket.uploadFromStream` returns a Buffer instead of an ObjectId.

### ISSUE THREAD

**Issue by c0per** [denodrivers/deno_mongo#271]
The doc says this method is supposed to return the ObjectId of the newly uploaded file. But it's returning the result of `ObjectId.generate()`, which is a Buffer.

**Comment by c0per** [comment]
As I made this very tiny fix in #272 , if it is not intended.

**Comment by lucsoft** [comment]
@erfanium do you want to close this issue?
