### ISSUE TITLE
Older MongoDB versions are not supported

### ISSUE THREAD

**Issue by arjun-1** [denodrivers/deno_mongo#288]
When trying to connect to a v3.4.7 MongoDB:
```typescript
const client = new MongoClient()
await client.connect('mongodb://localhost:27017');
```

deno_mongo throws an assertion error:
```bash
error: Uncaught (in promise) AssertionError
    throw new AssertionError(msg);
          ^
    at assert (https://deno.land/std@0.111.0/testing/asserts.ts:224:11)
    at WireProtocol.receive (https://deno.land/x/mongo@v0.28.0/src/protocol/protocol.ts:101:7)
```

expected behaviour is that deno_mongo either supports this version, or exits telling it does not.

**Comment by erfanium** [comment]
This driver only supports 4.0 to 4.6 mongodb versions. we may add support for version 5 soon but not sure for older versions
