### ISSUE TITLE
chore(deps): drop `std/hash` dependency 

### ISSUE THREAD

**Issue by erfanium** [denodrivers/deno_mongo#299]
std/hash module has been deprecated and should be replaced with webcrypto apis.

Our usage from `std/hash`
- [x] sha1 hash 
- [x] sha256 hash
- [ ] md5 hsah (webcrypto doesn't supported it yet) (see https://github.com/denoland/deno/pull/12793)

**Comment by jeremyBanks** [comment]
`std/crypto` provides a wrapper for WebCrypto that provides a WASM implementation of MD5, behind the same interface:

**Comment by erfanium** [comment]
@jeremyBanks Thank you for the help!
