### ISSUE TITLE
Can you lock the bson version?

### ISSUE THREAD

**Issue by jiawei397** [denodrivers/deno_mongo#305]
Thanks a lot. This is a very good project and we are using it. 

But when I use lock.json, I meet that the CDN file hash will change always.

Can you lock the [bson](https://github.com/denodrivers/deno_mongo/blob/a7ac283cfefaf194ac0dfa586a2e784f8dfc6d1b/bson/bson.ts) version like this?

```
https://cdn.skypack.dev/pin/bson@v4.5.4-F38JF4sWndM08oQ5WCDI/mode=imports/optimized/bson.js
```

**Comment by manyuanrong** [comment]
https://github.com/denodrivers/deno_mongo/pull/290
The fixed bson version was rolled back in this issue because the bson.d.ts file provided by skypack failed the type check in deno.
I don’t know if the problem has been resolved

**Comment by jiawei397** [comment]
This is really sad news. If you don't care about the bson version, you can try the package I released. It is based on version 4.5.3.
```
https://deno.land/x/deno_bson@v0.0.2
```
Otherwise, I have to give up lock.json for a while.

**Comment by manyuanrong** [comment]
@erfanium Have you tried importing on jspm before?

**Comment by erfanium** [comment]
@jiawei397 
Do you mean this? #306

**Comment by erfanium** [comment]
@manyuanrong 
> Have you tried importing on jspm before?

jspm doesn't support `.d.ts` bundle file, so it doesn't matter to us whether use it or not.
skypack's js bundle for bson is very tiny, so i pick skypack over jspm and esm.sh

**Comment by jiawei397** [comment]
> @jiawei397 Do you mean this? #306

I got the answer by this: https://github.com/denoland/deno/discussions/12955

I hoped it will work.

**Comment by erfanium** [comment]
yeah, that's it
