### ISSUE TITLE
How can create a text index?

### ISSUE THREAD

**Issue by jiawei397** [denodrivers/deno_mongo#312]
I may need this feature now to support `$text` and `$search`. Just like this: https://docs.mongodb.com/manual/core/index-text/#create-text-index and https://docs.mongodb.com/manual/text-search/.

**Comment by erfanium** [comment]
```ts
import { MongoClient } from "./mod.ts";

const client = new MongoClient();
await client.connect("mongodb://localhost:27017/test");

const db = client.database("test");
const col = db.collection("test");

await col.createIndexes({
  indexes: [
    {
      key: {
        title: "text",
      },
      name: "title_text_index",
    },
  ],
});

await col.insertMany([{
  title: "hi there, i'm mongo",
}, {
  title: "you can search me",
}]);

const result = await col.find({
  $text: {
    $search: "mongo",
  },
}).toArray();

console.log(result);
```

**Comment by jiawei397** [comment]
> ```ts
> const client = new MongoClient();
> await client.connect("mongodb://localhost:27017/test");
> 
> const db = client.database("test");
> const col = db.collection("test");
> 
> await col.createIndexes({
>   indexes: [
>     {
>       key: {
>         title: "text",
>       },
>       name: "title_text_index",
>     },
>   ],
> });
> 
> await col.insertMany([{
>   title: "hi there, i'm mongo",
> }, {
>   title: "you can search me",
> }]);
> 
> const result = await col.find({
>   $text: {
>     $search: "mongo",
>   },
> }).toArray();
> 
> console.log(result);
> ```

Perfect! Thank you for your answer！
