### ISSUE TITLE
createIndexes: panicked at 'not implemented'

### ISSUE THREAD

**Issue by closet6** [denodrivers/deno_mongo#33]
when trying to create an index like below,

```
users.createIndexes([
  {
    keys: { email: 1 },
    options: { unique: true },
  },
]);
```

i get this error:

```
api_1  | [IndexModel { keys: OrderedDocument({"email": I64(1)}), options: Some(OrderedDocument({"unique": Boolean(true)})) }]
api_1  | thread '<unnamed>' panicked at 'not implemented', <::std::macros::panic macros>:2:4
api_1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

am i calling it wrong, or does not implemented mean here that its not ready to be called yet?

tia

**Comment by manyuanrong** [comment]
This project is based on the MongoDB official driver library package, the official library currently does not implement this function

**Comment by quenginedev** [comment]
Is there a way in which we could create unique indexes using the MongoClient library?

**Comment by Guillaume-Lebegue** [comment]
I'm updating this since I need to do some text search.

Is there some ETA on createIndexes?
Or a way to create indexes?

**Comment by rvdende** [comment]
I'm running into this now migrating a codebase from node to deno. 
Previously used https://www.npmjs.com/package/mongojs#api which has db.collection.createIndex() .
I'm thinking now as a workaround I'll spawn a child process "mongo" and automate the creation of Indexes from the cli client.

**Comment by manyuanrong** [comment]
The project has been refactored and now needs to implement this function on the new architecture

**Comment by manyuanrong** [comment]
v0.21.0 is supported
