### ISSUE TITLE
FindCursorContext.options are shared between requests and affect the output

### ISSUE THREAD

**Issue by FSou1** [denodrivers/deno_mongo#330]
If I reuse a single instance of `MongoClient` between independent requests, a `limit` value of one request limits the number of items of the second request.

I use a single client for all my requests:

```typescript
const FIND_OPTIONS: FindOptions = { noCursorTimeout: false };

const client = new MongoClient();

try {
  await client.connect({ ... });
} catch (err) {
  console.error('Error connecting to MongoDB', err);
  throw err;
}

const database = () => {
  return client.database("test");
};
```

First request has the `limit` call:
```typescript
export const allPositions = async (limit: number, offset: number) => {
  const db = database();

  const positions = db.collection<PositionSchema>("positions");

  return await positions.find(filter, FIND_OPTIONS).skip(offset).limit(limit).toArray();
}
```

Second request is supposed to return all items:
```typescript
export const allLocations = async () => {
  const db = database();

  const locations = db.collection<PositionSchema>("locations");

  const items = await locations.find({}, FIND_OPTIONS).toArray();

  return items;
}
```

Output:
- **/allLocations** Returns 70 locations (70/70)
- **/allPositions?limit=30** Returns 30 positions
- **/allLocations** Returns 30 locations (30/70)
- **/allPositions?limit=5** Returns 5 positions (because `limit` equals to `5)
- **/allLocations** Returns 5 locations (5/70)

If this is the expected behavior, how should I manage the MongoDB connections then?

**Comment by erfanium** [comment]
Thank you for submitting this issue. I'll check it out on the weekend

**Comment by FSou1** [comment]
The problem is in this line:

```
const FIND_OPTIONS: FindOptions = { noCursorTimeout: false };
```

If I had created a new `FindOptions` object for each call, I wouldn't have faced this issue.

I don't know if you consider this as an issue, but I've created a PR just in case.

The PR creates a new options object every time you call `skip`, `limit`, and `sort`.
