### ISSUE TITLE
Unable to use GeoJSON point as the value of `$nearSphere` operator

### ISSUE THREAD

**Issue by Jaysok** [denodrivers/deno_mongo#341]
It seems the type of `$nearSphere` operator defined in `FilterOperators` only supports legacy coordinate point.

```typescript
interface FilterOperators<TValue> extends Document {
  // [...]
  $nearSphere?: TValue;
  // [...]
}
```

given the type `Place` below

```typescript
interface Place {
  name: string;
  location: [number, number];
}

let placeCollection: Collection<Place> = await getPlaceCollection();
```

#### case 1. GeoJSON point (which is not supported)
```typescript
placeCollection.find(
  {
    location: {
       $nearSphere: { // <-- (?) doesn't work
          $geometry: { 
             type : "Point",
             coordinates : [ -73.9667, 40.78 ]  
          },
          $minDistance: 1000,
          $maxDistance: 5000
       }
    }
  }
)
```

#### case 2. Legacy coordinate point
```typescript
placeCollection.find(
  {
    location: {
       $nearSphere: [ -73.9667, 40.78 ]   // (!) works
    }
  }
)
```

IMO it should be something like this, so it can support GeoJSON point also
```typescript
interface FilterOperators<TValue> extends Document {
  // [...]
  $nearSphere?: TValue | Document;
  // [...]
}
```

##### Links for your conveinence
- [`FilterOperators<T>`](https://deno.land/x/mongo@v0.29.3/src/types.ts#L629)
- [Official Mongo `$nearSphere`](https://www.mongodb.com/docs/manual/reference/operator/query/nearSphere/#-nearsphere)

**Comment by ralyodio** [comment]
I’m also wondering how to find places with a 30 mile radius using this module. 

Is it possible?

can you add to tests?

**Comment by erfanium** [comment]
@ralyodio queries are not driver related. you can use any mongodb queries you want with this friver
