### ISSUE TITLE
field required true

### ISSUE THREAD

**Issue by KjshServer** [denodrivers/deno_mongo#348]
hi, I have the following code

db.ts:

`
import { MongoClient } from "https://deno.land/x/mongo@v0.29.3/mod.ts"

const client = new MongoClient()

const dbConnect = async () => {
	await client
		.connect("mongodb://sammy:123456789@127.0.0.1:27017/crud?authSource=admin")
		.then(() => {
			console.log("Connected to MongoDB")
		})
		.catch(err => {
			console.log(err.message)
		})
}

export { dbConnect, client }
`

iuser.ts:

`
interface iUser {
	firstName: string
	lastName: string
	nickName: string
	email: string
	password: string
	role: string
}
`
users.ts

`
import { dbConnect, client } from "../../settings/db.ts"
import { iUser } from "../../interfaces/iuser.ts"

await dbConnect()

const User = client.database().collection<iUser>("users")

User.createIndexes({
	indexes: [
		{
			name: "nickName",
			key: {
				nickName: 1
			},
			min: 3,
			unique: true
		},
		{
			name: "email",
			key: {
				email: 2
			},
			min: 6,
			unique: true
		}
	]
})

export default User
`

how to add required true to nickName, email and password

:)

**Comment by erfanium** [comment]
The driver won't validate you documents. you can either validate request by yourself (recommended) or use [MongoDB collection schema feature](https://www.mongodb.com/docs/manual/core/schema-validation/)
