### ISSUE TITLE
Uncaught BSONTypeError: Argument passed in must be a string of 12 bytes or a string of 24 hex characters

### ISSUE THREAD

**Issue by KnorpelSenf** [denodrivers/deno_mongo#350]
I would like to use arbitrary string values as my object identifiers. However, when I pass e.g. `'1234'` to the `ObjectId` constructor by running
```ts
let _id = new ObjectId('1234')
```
then the error
```
Uncaught BSONTypeError: Argument passed in must be a string of 12 bytes or a string of 24 hex characters
    at new ObjectId (https://deno.land/x/web_bson@v0.2.1/src/objectid.ts:77:15)
    at <anonymous>:2:11
```
is thrown.

**Comment by erfanium** [comment]
ObjectId is defined as a 12 byte length structured Uint8Array in bson specifications. you can't modify it.

use plain strings as you document primary keys:
```js
let _id: '1234'
```
