### ISSUE TITLE
feat: support database.createCollection

### ISSUE THREAD

**Issue by idanran** [denodrivers/deno_mongo#352]
I think it would be better to support `database.createCollection`

**Comment by lucsoft** [comment]
What is the difference between now?
This kinda seams unnecessary

**Comment by erfanium** [comment]
@lucsoft `db.createCollection(...)` is not like `db.collection(...)`. createCollection method is used to set extra configs to the collection (like schema validations)
https://www.mongodb.com/docs/manual/reference/command/create/
